name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  whotogreet1:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  whotogreet2:  # id of input
    description: 'Who to greet'
    required: true
    default: 'MG'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
